version: '3.1'

services:
  zoo1:
    image: zookeeper:latest
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper:latest
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper:latest
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      
  db1:
    image: zookeeper_demo:latest
    hostname: db1
    ports:
      - 8081:8081
    environment:
      ZOOKEEPER: zoo1:2181

  db2:
    image: zookeeper_demo:latest
    hostname: db2
    ports:
      - 8082:8081
    environment:
      ZOOKEEPER: zoo1:2181

  db3:
    image: zookeeper_demo:latest
    hostname: db3
    ports:
      - 8083:8081
    environment:
      ZOOKEEPER: zoo2:2181
